const menu = {
    list() {
        return [
    {
        "backMenu":[
        ],
        "frontMenu":[
        ],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    },
    {
        "backMenu":[
			{
                "child":[
                    {
						"appFrontIcon":"cuIcon-form",
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"体检记录",
                        "menuJump":"列表",
                        "tableName":"gerentizheng"
                    }
                ],
                "menu":"体检记录"
            },
			{
                "child":[
                    {
						"appFrontIcon":"cuIcon-form",
                        "buttons":[
                            "查看",
                        ],
                        "menu":"健康食谱",
                        "menuJump":"列表",
                        "tableName":"meishi"
                    }
                ],
                "menu":"健康食谱"
            },
			{
                "child":[
                    {
						"appFrontIcon":"cuIcon-form",
                        "buttons":[
                            "查看",
                        ],
                        "menu":"药品信息",
                        "menuJump":"列表",
                        "tableName":"yaopin"
                    }
                ],
                "menu":"药品信息"
            }
			,
			{
                "child":[
                    {
						"appFrontIcon":"cuIcon-form",
                        "buttons":[
                            "查看",
                        ],
                        "menu":"运动教程",
                        "menuJump":"列表",
                        "tableName":"yundong"
                    }
                ],
                "menu":"运动教程"
            }
			,
			{
                "child":[
                    {
						"appFrontIcon":"cuIcon-form",
                        "buttons":[
                            "查看",
                        ],
                        "menu":"健康贴士",
                        "menuJump":"列表",
                        "tableName":"jiankangtieshi"
                    }
                ],
                "menu":"健康贴士"
            }
			,
			{
                "child":[
                    {
						"appFrontIcon":"cuIcon-form",
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"每日计划",
                        "menuJump":"列表",
                        "tableName":"meirijihua"
                    }
                ],
                "menu":"每日计划"
            }
			
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-favor",
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"健康食谱收藏",
                        "menuJump":"列表",
                        "tableName":"meishiCollection"
                    }
                ],
                "menu":"健康食谱收藏"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-evaluate",
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"健康食谱留言",
                        "menuJump":"列表",
                        "tableName":"meishiLiuyan"
                    }
                ],
                "menu":"健康食谱留言"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-activity",
                        "buttons":[
                            "查看"
                        ],
                        "menu":"公告信息",
                        "menuJump":"列表",
                        "tableName":"news"
                    }
                ],
                "menu":"公告信息"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-favor",
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"运动教程收藏",
                        "menuJump":"列表",
                        "tableName":"yundongCollection"
                    }
                ],
                "menu":"运动教程收藏"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-evaluate",
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"运动教程留言",
                        "menuJump":"列表",
                        "tableName":"yundongLiuyan"
                    }
                ],
                "menu":"运动教程留言"
            }
        ],
        "frontMenu":[
        ],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"是",
        "hasFrontRegister":"是",
        "roleName":"用户",
        "tableName":"yonghu"
    }
]

	}
}
export default menu;
